layout_spectrum: 0.001918857917189598
typography_spectrum: 0.6067082781810313
color:
  brandColors:
    - '#ffffff'
    - '#d2d097'
    - '#455f82'
    - '#9fada0'
    - '#677c98'
  brandStrength: 0.6338800697121769
  lightness: 0.738076239824295
  saturation: 0.5337037888821214
  rhythmicContrast: 0.6591181070543826
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Tapintu
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Tapintu
description: Insight Facilitation
purpose: []
